local Shared = require(script.Parent:WaitForChild("Shared"))

return {
	Shared.CreateFood({
		ItemId = "hay_bale",
		DisplayName = "Hay Bale",
		Description = "Basic hay that fills the stomach well, but keeps excitement low.",
		Price = 1,
		PriceLabel = "1 coin",
		SortOrder = 10,
		Effects = {
			NeedGain = 22,
			HappinessGain = 3,
			HealthGain = 0,
			FriendshipGain = 2,
			OverflowYield = 0.24,
			OverflowHealthPenalty = 0.18,
			OverflowHappinessFactor = 0.25,
			DecayBuff = {
				Multiplier = 0.92,
				DurationMinutes = 12,
			},
			MoodText = "Satisfied",
		},
		Tags = { "Hay", "Starter" },
	}),
	Shared.CreateFood({
		ItemId = "apple_treat",
		DisplayName = "Apple Treat",
		Description = "A light snack that fills less, but gives a strong happiness bump.",
		Price = 2,
		PriceLabel = "2 coin",
		SortOrder = 20,
		Effects = {
			NeedGain = 12,
			HappinessGain = 10,
			HealthGain = 0,
			FriendshipGain = 5,
			OverflowYield = 0.35,
			OverflowHealthPenalty = 0.12,
			OverflowHappinessFactor = 0.4,
			DecayBuff = {
				Multiplier = 0.96,
				DurationMinutes = 6,
			},
			MoodText = "Cheerful",
		},
		Tags = { "Treat", "Sweet" },
	}),
	Shared.CreateFood({
		ItemId = "carrot_bunch",
		DisplayName = "Carrot Bunch",
		Description = "Balanced carrots that feed well and still keep the horse in a good mood.",
		Price = 3,
		PriceLabel = "3 coin",
		SortOrder = 30,
		Effects = {
			NeedGain = 18,
			HappinessGain = 7,
			HealthGain = 1,
			FriendshipGain = 4,
			OverflowYield = 0.3,
			OverflowHealthPenalty = 0.15,
			OverflowHappinessFactor = 0.36,
			DecayBuff = {
				Multiplier = 0.9,
				DurationMinutes = 8,
			},
			MoodText = "Content",
		},
		Tags = { "Treat", "Balanced" },
	}),
	Shared.CreateFood({
		ItemId = "apple_fruit",
		DisplayName = "Apple",
		ToolName = "Apple",
		Description = "Freshly harvested apple from the farm.",
		Price = 8,
		PriceLabel = "8 horseshoes",
		SortOrder = 35,
		CareType = false,
		NeedKey = false,
		InventoryPath = "Fruits",
		ShopId = false,
		EffectsSummary = "Harvested farming fruit",
		Tags = { "Farming", "Fruit" },
	}),
	Shared.CreateFood({
		ItemId = "carrot_fruit",
		DisplayName = "Carrot",
		ToolName = "Carrot",
		Description = "Freshly harvested carrot from the farm.",
		Price = 5,
		PriceLabel = "5 horseshoes",
		SortOrder = 36,
		CareType = false,
		NeedKey = false,
		InventoryPath = "Fruits",
		ShopId = false,
		EffectsSummary = "Harvested farming fruit",
		Tags = { "Farming", "Fruit" },
	}),
	Shared.CreateFood({
		ItemId = "mint_treat",
		DisplayName = "Mint Treat",
		Description = "A favorite bonding snack that gives modest food and extra happiness.",
		Price = 4,
		PriceLabel = "4 coin",
		SortOrder = 40,
		Effects = {
			NeedGain = 10,
			HappinessGain = 12,
			HealthGain = 0,
			FriendshipGain = 6,
			OverflowYield = 0.38,
			OverflowHealthPenalty = 0.1,
			OverflowHappinessFactor = 0.45,
			DecayBuff = {
				Multiplier = 0.82,
				DurationMinutes = 10,
			},
			MoodText = "Playful",
		},
		Tags = { "Treat", "Bonding" },
	}),
	Shared.CreateFood({
		ItemId = "oat_crunch",
		DisplayName = "Oat Crunch",
		Description = "Dry oats that are simple and steady, with a longer fullness effect.",
		Price = 5,
		PriceLabel = "5 coin",
		SortOrder = 50,
		Effects = {
			NeedGain = 16,
			HappinessGain = 5,
			HealthGain = 0,
			FriendshipGain = 3,
			OverflowYield = 0.28,
			OverflowHealthPenalty = 0.14,
			OverflowHappinessFactor = 0.32,
			DecayBuff = {
				Multiplier = 0.88,
				DurationMinutes = 14,
			},
			MoodText = "Calm",
		},
		Tags = { "Oats", "Steady" },
	}),
	Shared.CreateFood({
		ItemId = "clover_mix",
		DisplayName = "Clover Mix",
		Description = "A softer meal that feeds less than hay, but stretches hunger decay longer.",
		Price = 6,
		PriceLabel = "6 coin",
		SortOrder = 60,
		Effects = {
			NeedGain = 14,
			HappinessGain = 8,
			HealthGain = 0,
			FriendshipGain = 4,
			OverflowYield = 0.32,
			OverflowHealthPenalty = 0.11,
			OverflowHappinessFactor = 0.38,
			DecayBuff = {
				Multiplier = 0.8,
				DurationMinutes = 16,
			},
			MoodText = "Relaxed",
		},
		Tags = { "Clover", "SlowDecay" },
	}),
	Shared.CreateFood({
		ItemId = "beet_pellets",
		DisplayName = "Beet Pellets",
		Description = "Dense pellets that feed well and give a small health top-up.",
		Price = 7,
		PriceLabel = "7 coin",
		SortOrder = 70,
		Effects = {
			NeedGain = 20,
			HappinessGain = 4,
			HealthGain = 2,
			FriendshipGain = 3,
			OverflowYield = 0.22,
			OverflowHealthPenalty = 0.16,
			OverflowHappinessFactor = 0.24,
			DecayBuff = {
				Multiplier = 0.86,
				DurationMinutes = 18,
			},
			MoodText = "Restored",
		},
		Tags = { "Pellets", "Dense" },
	}),
	Shared.CreateFood({
		ItemId = "berry_mash",
		DisplayName = "Berry Mash",
		Description = "Soft mash that fills lightly, but gives one of the best happiness boosts.",
		Price = 8,
		PriceLabel = "8 coin",
		SortOrder = 80,
		Effects = {
			NeedGain = 11,
			HappinessGain = 13,
			HealthGain = 1,
			FriendshipGain = 7,
			OverflowYield = 0.4,
			OverflowHealthPenalty = 0.1,
			OverflowHappinessFactor = 0.5,
			DecayBuff = {
				Multiplier = 0.94,
				DurationMinutes = 7,
			},
			MoodText = "Delighted",
		},
		Tags = { "Mash", "Premium" },
	}),
	Shared.CreateFood({
		ItemId = "grain_scoop",
		DisplayName = "Grain Scoop",
		Description = "A heavy scoop that fills a lot, but is rougher when force-fed past the limit.",
		Price = 9,
		PriceLabel = "9 coin",
		SortOrder = 90,
		Effects = {
			NeedGain = 28,
			HappinessGain = 2,
			HealthGain = 0,
			FriendshipGain = 2,
			OverflowYield = 0.18,
			OverflowHealthPenalty = 0.22,
			OverflowHappinessFactor = 0.2,
			DecayBuff = {
				Multiplier = 0.87,
				DurationMinutes = 20,
			},
			MoodText = "Full",
		},
		Tags = { "Grain", "Heavy" },
	}),
	Shared.CreateFood({
		ItemId = "meadow_supper",
		DisplayName = "Meadow Supper",
		Description = "A large meal with the best food value and longest slowdown on hunger decay.",
		Price = 10,
		PriceLabel = "10 coin",
		SortOrder = 100,
		Effects = {
			NeedGain = 32,
			HappinessGain = 4,
			HealthGain = 1,
			FriendshipGain = 3,
			OverflowYield = 0.16,
			OverflowHealthPenalty = 0.26,
			OverflowHappinessFactor = 0.22,
			DecayBuff = {
				Multiplier = 0.78,
				DurationMinutes = 24,
			},
			MoodText = "Very Full",
		},
		Tags = { "Meal", "Large" },
	}),
}
