local Shared = require(script.Parent:WaitForChild("Shared"))

local FOOD_IMAGE_IDS = {
	hay_bale = "",
	bread = "",
	beet_pellets = "",
	berry_mash = "",
	root_salad = "",
	garden_soup = "",
	stuffed_pumpkin = "",
	harvest_skewers = "",
	golden_salad = "",
	golden_grain_loaf = "",
	diamond_root_feast = "",
	diamond_champion_bowl = "",
}

local function crafted_food(config)
	config.IdImage = config.IdImage or FOOD_IMAGE_IDS[config.ItemId] or ""
	config.ShopId = false
	config.Price = config.Price or 0
	config.PriceLabel = config.PriceLabel or "Crafted"
	config.EquipOnPurchase = false
	return Shared.CreateFood(config)
end

return {
	crafted_food({
		ItemId = "hay_bale",
		DisplayName = "Hay Bale",
		ToolName = "HaybaleTool",
		Description = "Basic bundled wheat that fills the stomach well, but keeps excitement low.",
		SortOrder = 10,
		Effects = {
			NeedGain = 22,
			HappinessGain = 3,
			HealthGain = 0,
			FriendshipGain = 2,
			OverflowYield = 0.24,
			OverflowHealthPenalty = 0.18,
			OverflowHappinessFactor = 0.25,
			DecayBuff = {
				Multiplier = 0.92,
				DurationMinutes = 12,
			},
			MoodText = "Satisfied",
		},
		Tags = { "Hay", "Starter", "Crafted" },
	}),
	crafted_food({
		ItemId = "bread",
		DisplayName = "Bread",
		Description = "Warm wheat bread that gives reliable food and a small comfort boost.",
		SortOrder = 20,
		Effects = {
			NeedGain = 24,
			HappinessGain = 5,
			HealthGain = 1,
			FriendshipGain = 3,
			OverflowYield = 0.26,
			OverflowHealthPenalty = 0.14,
			OverflowHappinessFactor = 0.3,
			DecayBuff = {
				Multiplier = 0.88,
				DurationMinutes = 15,
			},
			MoodText = "Comforted",
		},
		Tags = { "Bread", "Wheat", "Crafted" },
	}),
	crafted_food({
		ItemId = "beet_pellets",
		DisplayName = "Beet Pellets",
		Description = "Dense pellets that feed well and give a small health top-up.",
		SortOrder = 30,
		Effects = {
			NeedGain = 21,
			HappinessGain = 4,
			HealthGain = 3,
			FriendshipGain = 3,
			OverflowYield = 0.22,
			OverflowHealthPenalty = 0.16,
			OverflowHappinessFactor = 0.24,
			DecayBuff = {
				Multiplier = 0.86,
				DurationMinutes = 18,
			},
			MoodText = "Restored",
		},
		Tags = { "Pellets", "Root", "Crafted" },
	}),
	crafted_food({
		ItemId = "berry_mash",
		DisplayName = "Berry Mash",
		Description = "Soft mash that fills lightly, but gives a strong happiness boost.",
		SortOrder = 40,
		Effects = {
			NeedGain = 14,
			HappinessGain = 14,
			HealthGain = 1,
			FriendshipGain = 7,
			OverflowYield = 0.4,
			OverflowHealthPenalty = 0.1,
			OverflowHappinessFactor = 0.5,
			DecayBuff = {
				Multiplier = 0.93,
				DurationMinutes = 8,
			},
			MoodText = "Delighted",
		},
		Tags = { "Mash", "Sweet", "Crafted" },
	}),
	crafted_food({
		ItemId = "root_salad",
		DisplayName = "Root Salad",
		Description = "A crisp salad using several fresh vegetables from the farm.",
		SortOrder = 50,
		Effects = {
			NeedGain = 18,
			HappinessGain = 10,
			HealthGain = 2,
			FriendshipGain = 5,
			OverflowYield = 0.34,
			OverflowHealthPenalty = 0.11,
			OverflowHappinessFactor = 0.42,
			DecayBuff = {
				Multiplier = 0.84,
				DurationMinutes = 16,
			},
			MoodText = "Fresh",
		},
		Tags = { "Salad", "Vegetable", "Crafted" },
	}),
	crafted_food({
		ItemId = "garden_soup",
		DisplayName = "Garden Soup",
		Description = "A warm vegetable soup for steady hunger and health recovery.",
		SortOrder = 60,
		Effects = {
			NeedGain = 26,
			HappinessGain = 7,
			HealthGain = 3,
			FriendshipGain = 5,
			OverflowYield = 0.27,
			OverflowHealthPenalty = 0.13,
			OverflowHappinessFactor = 0.34,
			DecayBuff = {
				Multiplier = 0.82,
				DurationMinutes = 20,
			},
			MoodText = "Warmed",
		},
		Tags = { "Soup", "Vegetable", "Crafted" },
	}),
	crafted_food({
		ItemId = "stuffed_pumpkin",
		DisplayName = "Stuffed Pumpkin",
		Description = "A hearty pumpkin packed with grains and bright vegetables.",
		SortOrder = 70,
		Effects = {
			NeedGain = 30,
			HappinessGain = 6,
			HealthGain = 4,
			FriendshipGain = 5,
			OverflowYield = 0.23,
			OverflowHealthPenalty = 0.15,
			OverflowHappinessFactor = 0.3,
			DecayBuff = {
				Multiplier = 0.8,
				DurationMinutes = 24,
			},
			MoodText = "Hearty",
		},
		Tags = { "Pumpkin", "LargeMeal", "Crafted" },
	}),
	crafted_food({
		ItemId = "harvest_skewers",
		DisplayName = "Harvest Skewers",
		Description = "Roasted farm vegetables served in quick bite-sized pieces.",
		SortOrder = 80,
		Effects = {
			NeedGain = 20,
			HappinessGain = 9,
			HealthGain = 2,
			FriendshipGain = 4,
			OverflowYield = 0.31,
			OverflowHealthPenalty = 0.12,
			OverflowHappinessFactor = 0.4,
			DecayBuff = {
				Multiplier = 0.83,
				DurationMinutes = 18,
			},
			MoodText = "Focused",
		},
		Tags = { "Roasted", "Vegetable", "Crafted" },
	}),
	crafted_food({
		ItemId = "golden_salad",
		DisplayName = "Golden Salad",
		Description = "A rare salad that can only be crafted from Gold harvests.",
		SortOrder = 90,
		Effects = {
			NeedGain = 34,
			HappinessGain = 16,
			HealthGain = 6,
			FriendshipGain = 9,
			OverflowYield = 0.45,
			OverflowCap = 80,
			OverflowHealthPenalty = 0.07,
			OverflowHappinessFactor = 0.72,
			DecayBuff = {
				Multiplier = 0.62,
				DurationMinutes = 45,
			},
			HealthRegen = {
				TotalGain = 8,
				DurationMinutes = 12,
			},
			SecondaryNeedAdjustments = {
				Thirst = 4,
			},
			MoodText = "Golden",
		},
		Tags = { "Salad", "Gold", "Rare", "Crafted" },
	}),
	crafted_food({
		ItemId = "golden_grain_loaf",
		DisplayName = "Golden Grain Loaf",
		Description = "A rare loaf baked only from Gold grain and vegetables.",
		SortOrder = 100,
		Effects = {
			NeedGain = 40,
			HappinessGain = 12,
			HealthGain = 5,
			FriendshipGain = 8,
			OverflowYield = 0.4,
			OverflowCap = 85,
			OverflowHealthPenalty = 0.08,
			OverflowHappinessFactor = 0.65,
			DecayBuff = {
				Multiplier = 0.58,
				DurationMinutes = 50,
			},
			HealthRegen = {
				TotalGain = 10,
				DurationMinutes = 14,
			},
			SecondaryNeedAdjustments = {
				Cleanliness = 3,
			},
			MoodText = "Glowing",
		},
		Tags = { "Bread", "Gold", "Rare", "Crafted" },
	}),
	crafted_food({
		ItemId = "diamond_root_feast",
		DisplayName = "Diamond Root Feast",
		Description = "An extremely rare root feast that requires only Diamond harvests.",
		SortOrder = 110,
		Effects = {
			NeedGain = 48,
			HappinessGain = 22,
			HealthGain = 10,
			FriendshipGain = 12,
			OverflowYield = 0.52,
			OverflowCap = 105,
			OverflowHealthPenalty = 0.04,
			OverflowHappinessFactor = 0.85,
			DecayBuff = {
				Multiplier = 0.42,
				DurationMinutes = 80,
			},
			HealthRegen = {
				TotalGain = 18,
				DurationMinutes = 20,
			},
			SecondaryNeedAdjustments = {
				Thirst = 5,
				Cleanliness = 5,
			},
			MoodText = "Radiant",
		},
		Tags = { "Feast", "Diamond", "UltraRare", "Crafted" },
	}),
	crafted_food({
		ItemId = "diamond_champion_bowl",
		DisplayName = "Diamond Champion Bowl",
		Description = "The rarest champion meal, crafted entirely from Diamond harvests.",
		SortOrder = 120,
		Effects = {
			NeedGain = 56,
			HappinessGain = 26,
			HealthGain = 14,
			FriendshipGain = 15,
			OverflowYield = 0.58,
			OverflowCap = 120,
			OverflowHealthPenalty = 0.03,
			OverflowHappinessFactor = 0.9,
			DecayBuff = {
				Multiplier = 0.35,
				DurationMinutes = 100,
			},
			HealthRegen = {
				TotalGain = 24,
				DurationMinutes = 25,
			},
			SecondaryNeedAdjustments = {
				Thirst = 8,
				Cleanliness = 8,
			},
			MoodText = "Champion",
		},
		Tags = { "Bowl", "Diamond", "UltraRare", "Crafted" },
	}),
}
