local Shared = require(script.Parent:WaitForChild("Shared"))

return {
	Shared.CreateMisc({
		ShopId = "Noob",
		ItemId = "soap",
		DisplayName = "Soap",
		IconImage = "rbxassetid://84292972231295",
		Description = "Basic soap used to wash your horse and restore cleanliness.",
		Price = 2,
		PriceLabel = "2 coin",
		SortOrder = 10,
		Effects = {
			CleanlinessGain = 100,
			HappinessGain = 2,
			FriendshipGain = 2,
			MoodText = "Fresh",
		},
		PromptActionText = "Wash",
		PromptObjectText = "Your horse",
		ResponseCode = "Cleaned",
		Tags = { "Cleaning", "Soap" },
	}),
	Shared.CreateMisc({
		ShopId = "Noob",
		ItemId = "horse_brush",
		DisplayName = "Horse Brush",
		ToolGrip = CFrame.new(0, -0.48, -0.08)
			* CFrame.Angles(0, math.rad(12), math.rad(90)),
		IconImage = "rbxassetid://92561730155272",
		Description = "A soft brush used to calm your horse and make it feel cared for.",
		Price = 3,
		PriceLabel = "3 coin",
		SortOrder = 20,
		Effects = {
			HappinessGain = 5,
			MoodText = "Pampered",
		},
		EffectsSummary = "Happiness +5",
		PromptActionText = "Brush",
		PromptObjectText = "Your horse",
		ResponseCode = "Brushed",
		Tags = { "Grooming", "Brush" },
	}),
	Shared.CreateMisc({
		ShopId = "Noob",
		ItemId = "stable_broom",
		DisplayName = "Stable Broom",
		IconImage = "rbxassetid://100635115133388",
		Description = "A reusable broom for sweeping loose hay from occupied stalls.",
		Price = 8,
		PriceLabel = "8 coin",
		SortOrder = 30,
		MaxStack = 1,
		EffectsSummary = "Reusable | Cleans Loose Hay",
		Tags = { "Cleaning", "Stable", "Reusable" },
	}),
	Shared.CreateMisc({
		ShopId = "Noob",
		ItemId = "muck_fork",
		DisplayName = "Muck Fork",
		IconImage = "rbxassetid://122804690935823",
		Description = "A reusable stable fork made for removing manure safely.",
		Price = 12,
		PriceLabel = "12 coin",
		SortOrder = 40,
		MaxStack = 1,
		EffectsSummary = "Reusable | Cleans Manure",
		Tags = { "Cleaning", "Stable", "Reusable" },
	}),
	Shared.CreateMisc({
		ShopId = "Noob",
		ItemId = "cleaning_bucket",
		DisplayName = "Cleaning Bucket",
		IconImage = "rbxassetid://77008621798922",
		Description = "A reusable water bucket for rinsing muddy stall floors.",
		Price = 10,
		PriceLabel = "10 coin",
		SortOrder = 50,
		MaxStack = 1,
		EffectsSummary = "Reusable | Cleans Mud",
		Tags = { "Cleaning", "Stable", "Reusable" },
	}),
}
