local Shared = require(script.Parent:WaitForChild("Shared"))

return {
	Shared.CreateTack({
		ItemId = "starter_bridle",
		DisplayName = "Starter Bridle",
		IconImage = "",
		Description = "Simple tack for the first equipment set.",
		Price = 7,
		SortOrder = 10,
		EffectsSummary = "Starter tack item",
		Tags = { "Bridle", "Starter" },
	}),
	Shared.CreateTack({
		ShopId = "Cowboy",
		ItemId = "starter_saddle",
		DisplayName = "Starter Saddle",
		IconImage = "rbxassetid://91048216044527",
		Description = "A basic reusable saddle that gives a small speed bonus.",
		Price = 8,
		SortOrder = 20,
		EquipmentType = "Saddle",
		SaddleBonuses = {
			SprintSpeedAdd = 0.75,
		},
		EffectsSummary = "Sprint Speed +0.75",
		Tags = { "Saddle", "Starter" },
	}),
	Shared.CreateTack({
		ShopId = "Cowboy",
		ItemId = "trail_saddle",
		DisplayName = "Trail Saddle",
		IconImage = "rbxassetid://109493618578156",
		Description = "A comfortable saddle for long rides with better control and stamina.",
		Price = 25,
		SortOrder = 25,
		EquipmentType = "Saddle",
		SaddleBonuses = {
			TrotSpeedAdd = 0.5,
			TurnRateAdd = 0.04,
			StaminaAdd = 6,
		},
		EffectsSummary = "Trot +0.5 | Turn +0.04 | Stamina +6",
		Tags = { "Saddle", "Trail" },
	}),
	Shared.CreateTack({
		ShopId = "Cowboy",
		ItemId = "western_saddle",
		DisplayName = "Western Saddle",
		IconImage = "rbxassetid://94975031637704",
		Description = "A sturdy reusable saddle with a balanced mounted speed bonus.",
		Price = 40,
		SortOrder = 30,
		EquipmentType = "Saddle",
		SaddleBonuses = {
			CanterSpeedAdd = 0.75,
			SprintSpeedAdd = 1.5,
			AccelerationAdd = 0.02,
		},
		EffectsSummary = "Canter +0.75 | Sprint +1.5 | Acceleration +0.02",
		Tags = { "Saddle", "Western" },
	}),
	Shared.CreateTack({
		ShopId = "Cowboy",
		ItemId = "endurance_saddle",
		DisplayName = "Endurance Saddle",
		IconImage = "rbxassetid://124615692924907",
		Description = "A padded saddle built for stamina and smooth cross-country riding.",
		Price = 60,
		SortOrder = 35,
		EquipmentType = "Saddle",
		SaddleBonuses = {
			CanterSpeedAdd = 0.75,
			AccelerationAdd = 0.04,
			TurnRateAdd = 0.04,
			StaminaAdd = 12,
		},
		EffectsSummary = "Canter +0.75 | Acceleration +0.04 | Turn +0.04 | Stamina +12",
		Tags = { "Saddle", "Endurance" },
	}),
	Shared.CreateTack({
		ShopId = "Cowboy",
		ItemId = "english_saddle",
		DisplayName = "English Saddle",
		IconImage = "rbxassetid://131079709549740",
		Description = "A light reusable saddle tuned for fast riding and racing.",
		Price = 75,
		SortOrder = 40,
		EquipmentType = "Saddle",
		SaddleBonuses = {
			CanterSpeedAdd = 1,
			SprintSpeedAdd = 2.5,
			AccelerationAdd = 0.05,
			RaceAffinityAdd = 0.03,
		},
		EffectsSummary = "Canter +1 | Sprint +2.5 | Acceleration +0.05 | Race +0.03",
		Tags = { "Saddle", "English", "Race" },
	}),
	Shared.CreateTack({
		ShopId = "Cowboy",
		ItemId = "racing_saddle",
		DisplayName = "Racing Saddle",
		IconImage = "rbxassetid://120671474577442",
		Description = "An ultra-light saddle made for maximum sprint performance.",
		Price = 110,
		SortOrder = 50,
		EquipmentType = "Saddle",
		SaddleBonuses = {
			CanterSpeedAdd = 1.25,
			SprintSpeedAdd = 3.5,
			AccelerationAdd = 0.08,
			RaceAffinityAdd = 0.06,
		},
		EffectsSummary = "Canter +1.25 | Sprint +3.5 | Acceleration +0.08 | Race +0.06",
		Tags = { "Saddle", "Racing", "Race" },
	}),
	Shared.CreateTack({
		ShopId = "Cowboy",
		ItemId = "royal_saddle",
		DisplayName = "Royal Saddle",
		IconImage = "rbxassetid://138862844944672",
		Description = "A prestigious saddle with strong all-around riding bonuses.",
		Price = 180,
		SortOrder = 60,
		EquipmentType = "Saddle",
		SaddleBonuses = {
			TrotSpeedAdd = 0.75,
			CanterSpeedAdd = 1.5,
			SprintSpeedAdd = 3,
			AccelerationAdd = 0.06,
			TurnRateAdd = 0.06,
			StaminaAdd = 10,
			RaceAffinityAdd = 0.05,
		},
		EffectsSummary = "All-around premium riding bonuses",
		Tags = { "Saddle", "Royal", "Premium" },
	}),
}
