local Shared = require(script.Parent:WaitForChild("Shared"))

return {
	Shared.CreateWater({
		ItemId = "fresh_bucket",
		DisplayName = "Fresh Bucket",
		Description = "Basic water with reliable thirst recovery and no extra frills.",
		Price = 1,
		PriceLabel = "1 coin",
		SortOrder = 10,
		Effects = {
			NeedGain = 20,
			HappinessGain = 2,
			HealthGain = 0,
			FriendshipGain = 2,
			OverflowYield = 0.3,
			OverflowHealthPenalty = 0.14,
			OverflowHappinessFactor = 0.22,
			DecayBuff = {
				Multiplier = 0.92,
				DurationMinutes = 10,
			},
			MoodText = "Hydrated",
		},
		Tags = { "Starter", "Basic" },
	}),
	Shared.CreateWater({
		ItemId = "cool_stream",
		DisplayName = "Cool Stream",
		Description = "Less thirst fill than a full bucket, but better comfort and recovery.",
		Price = 2,
		PriceLabel = "2 coin",
		SortOrder = 20,
		Effects = {
			NeedGain = 15,
			HappinessGain = 6,
			HealthGain = 0,
			FriendshipGain = 4,
			OverflowYield = 0.36,
			OverflowHealthPenalty = 0.1,
			OverflowHappinessFactor = 0.35,
			DecayBuff = {
				Multiplier = 0.88,
				DurationMinutes = 12,
			},
			MoodText = "Refreshed",
		},
		Tags = { "Comfort", "Balanced" },
	}),
	Shared.CreateWater({
		ItemId = "mint_infusion",
		DisplayName = "Mint Infusion",
		Description = "Light water that does not quench as much, but keeps the horse extra happy.",
		Price = 3,
		PriceLabel = "3 coin",
		SortOrder = 30,
		Effects = {
			NeedGain = 12,
			HappinessGain = 10,
			HealthGain = 0,
			FriendshipGain = 6,
			OverflowYield = 0.4,
			OverflowHealthPenalty = 0.09,
			OverflowHappinessFactor = 0.45,
			DecayBuff = {
				Multiplier = 0.8,
				DurationMinutes = 14,
			},
			MoodText = "Bright",
		},
		Tags = { "Mint", "Happy" },
	}),
	Shared.CreateWater({
		ItemId = "apple_splash",
		DisplayName = "Apple Splash",
		Description = "A sweet water mix that makes the horse happier than plain water.",
		Price = 4,
		PriceLabel = "4 coin",
		SortOrder = 40,
		Effects = {
			NeedGain = 14,
			HappinessGain = 8,
			HealthGain = 0,
			FriendshipGain = 5,
			OverflowYield = 0.35,
			OverflowHealthPenalty = 0.1,
			OverflowHappinessFactor = 0.4,
			DecayBuff = {
				Multiplier = 0.9,
				DurationMinutes = 8,
			},
			MoodText = "Pleased",
		},
		Tags = { "Sweet", "Treat" },
	}),
	Shared.CreateWater({
		ItemId = "spring_water",
		DisplayName = "Spring Water",
		Description = "Strong thirst recovery with a steady slowdown on future thirst decay.",
		Price = 5,
		PriceLabel = "5 coin",
		SortOrder = 50,
		Effects = {
			NeedGain = 24,
			HappinessGain = 3,
			HealthGain = 0,
			FriendshipGain = 3,
			OverflowYield = 0.24,
			OverflowHealthPenalty = 0.15,
			OverflowHappinessFactor = 0.24,
			DecayBuff = {
				Multiplier = 0.89,
				DurationMinutes = 18,
			},
			MoodText = "Cool",
		},
		Tags = { "Spring", "Steady" },
	}),
	Shared.CreateWater({
		ItemId = "rain_barrel",
		DisplayName = "Rain Barrel",
		Description = "A soft refill that is not fancy, but keeps thirst dropping slower for longer.",
		Price = 6,
		PriceLabel = "6 coin",
		SortOrder = 60,
		Effects = {
			NeedGain = 18,
			HappinessGain = 4,
			HealthGain = 0,
			FriendshipGain = 3,
			OverflowYield = 0.26,
			OverflowHealthPenalty = 0.13,
			OverflowHappinessFactor = 0.26,
			DecayBuff = {
				Multiplier = 0.86,
				DurationMinutes = 20,
			},
			MoodText = "Settled",
		},
		Tags = { "Barrel", "SlowDecay" },
	}),
	Shared.CreateWater({
		ItemId = "electrolyte_mix",
		DisplayName = "Electrolyte Mix",
		Description = "A stronger water mix that gives thirst back fast and helps health a bit.",
		Price = 7,
		PriceLabel = "7 coin",
		SortOrder = 70,
		Effects = {
			NeedGain = 22,
			HappinessGain = 5,
			HealthGain = 2,
			FriendshipGain = 4,
			OverflowYield = 0.23,
			OverflowHealthPenalty = 0.16,
			OverflowHappinessFactor = 0.28,
			DecayBuff = {
				Multiplier = 0.82,
				DurationMinutes = 16,
			},
			MoodText = "Recovered",
		},
		Tags = { "Recovery", "Health" },
	}),
	Shared.CreateWater({
		ItemId = "herbal_cooler",
		DisplayName = "Herbal Cooler",
		Description = "A calmer drink with lower thirst fill, but one of the best mood gains.",
		Price = 8,
		PriceLabel = "8 coin",
		SortOrder = 80,
		Effects = {
			NeedGain = 13,
			HappinessGain = 9,
			HealthGain = 1,
			FriendshipGain = 6,
			OverflowYield = 0.33,
			OverflowHealthPenalty = 0.09,
			OverflowHappinessFactor = 0.42,
			DecayBuff = {
				Multiplier = 0.78,
				DurationMinutes = 22,
			},
			MoodText = "Peaceful",
		},
		Tags = { "Herbal", "Mood" },
	}),
	Shared.CreateWater({
		ItemId = "glacier_sip",
		DisplayName = "Glacier Sip",
		Description = "A cold premium drink that restores a lot of thirst, but is less forgiving in excess.",
		Price = 9,
		PriceLabel = "9 coin",
		SortOrder = 90,
		Effects = {
			NeedGain = 26,
			HappinessGain = 4,
			HealthGain = 0,
			FriendshipGain = 3,
			OverflowYield = 0.2,
			OverflowHealthPenalty = 0.17,
			OverflowHappinessFactor = 0.24,
			DecayBuff = {
				Multiplier = 0.84,
				DurationMinutes = 24,
			},
			MoodText = "Recharged",
		},
		Tags = { "Cold", "Premium" },
	}),
	Shared.CreateWater({
		ItemId = "golden_trough",
		DisplayName = "Golden Trough",
		Description = "An expensive full drink that restores a lot and keeps thirst low for a long time.",
		Price = 10,
		PriceLabel = "10 coin",
		SortOrder = 100,
		Effects = {
			NeedGain = 30,
			HappinessGain = 6,
			HealthGain = 2,
			FriendshipGain = 5,
			OverflowYield = 0.18,
			OverflowHealthPenalty = 0.2,
			OverflowHappinessFactor = 0.28,
			DecayBuff = {
				Multiplier = 0.76,
				DurationMinutes = 28,
			},
			MoodText = "Pampered",
		},
		Tags = { "Large", "Luxury" },
	}),
}
