local Shared = require(script.Parent:WaitForChild("Shared"))

return {
	Shared.CreateWater({
		ShopId = false,
		ItemId = "fresh_bucket",
		DisplayName = "Fresh Bucket",
		IconImage = "rbxassetid://120519406655185",
		Description = "Basic water with reliable thirst recovery and no extra frills.",
		Price = 1,
		PriceLabel = "1 coin",
		SortOrder = 10,
		Effects = {
			NeedGain = 20,
			HappinessGain = 2,
			HealthGain = 0,
			FriendshipGain = 2,
			OverflowYield = 0.3,
			OverflowHealthPenalty = 0.14,
			OverflowHappinessFactor = 0.22,
			DecayBuff = {
				Multiplier = 0.92,
				DurationMinutes = 10,
			},
			MoodText = "Hydrated",
		},
		Tags = { "Starter", "Basic" },
	}),
	Shared.CreateWater({
		ShopId = "Cowboy",
		ItemId = "berry_splash",
		DisplayName = "Berry Splash",
		IconImage = "rbxassetid://88058124848481",
		ToolGrip = CFrame.new(0, -0.12, -0.48)
			* CFrame.Angles(math.rad(-12), math.rad(8), math.rad(-8)),
		Description = "A sweet berry-flavored drink that makes the horse happier while restoring a fair amount of thirst.",
		Price = 4,
		PriceLabel = "4 coin",
		SortOrder = 40,
		Effects = {
			NeedGain = 14,
			HappinessGain = 8,
			HealthGain = 0,
			FriendshipGain = 5,
			OverflowYield = 0.35,
			OverflowHealthPenalty = 0.10,
			OverflowHappinessFactor = 0.40,
			DecayBuff = {
				Multiplier = 0.90,
				DurationMinutes = 8,
			},
			MoodText = "Pleased",
		},
		Tags = { "Sweet", "Treat" },
	}),

	Shared.CreateWater({
		ShopId = "Cowboy",
		ItemId = "herbal_cooler",
		DisplayName = "Herbal Cooler",
		IconImage = "rbxassetid://136332130942031",
		Description = "A refreshing herbal drink that provides a calming effect and greatly improves the horse's mood.",
		Price = 8,
		PriceLabel = "8 coin",
		SortOrder = 80,
		Effects = {
			NeedGain = 13,
			HappinessGain = 9,
			HealthGain = 1,
			FriendshipGain = 6,
			OverflowYield = 0.33,
			OverflowHealthPenalty = 0.09,
			OverflowHappinessFactor = 0.42,
			DecayBuff = {
				Multiplier = 0.78,
				DurationMinutes = 22,
			},
			MoodText = "Peaceful",
		},
		Tags = { "Herbal", "Mood" },
	}),

	Shared.CreateWater({
		ShopId = "Cowboy",
		ItemId = "sparkling_water",
		DisplayName = "Sparkling Water",
		IconImage = "rbxassetid://88534252712128",
		Description = "A fizzy drink that refreshes the horse quickly and provides a small happiness boost.",
		Price = 5,
		PriceLabel = "5 coin",
		SortOrder = 50,
		Effects = {
			NeedGain = 20,
			HappinessGain = 5,
			HealthGain = 0,
			FriendshipGain = 4,
			OverflowYield = 0.28,
			OverflowHealthPenalty = 0.13,
			OverflowHappinessFactor = 0.30,
			DecayBuff = {
				Multiplier = 0.85,
				DurationMinutes = 15,
			},
			MoodText = "Refreshed",
		},
		Tags = { "Sparkling", "Refreshing" },
	}),

	Shared.CreateWater({
		ShopId = "Cowboy",
		ItemId = "apple_splash",
		DisplayName = "Apple Splash",
		IconImage = "rbxassetid://98185456479237",
		Description = "A crisp apple-flavored drink that restores thirst and leaves the horse feeling cheerful.",
		Price = 6,
		PriceLabel = "6 coin",
		SortOrder = 60,
		Effects = {
			NeedGain = 18,
			HappinessGain = 7,
			HealthGain = 1,
			FriendshipGain = 5,
			OverflowYield = 0.30,
			OverflowHealthPenalty = 0.12,
			OverflowHappinessFactor = 0.36,
			DecayBuff = {
				Multiplier = 0.83,
				DurationMinutes = 18,
			},
			MoodText = "Cheerful",
		},
		Tags = { "Apple", "Sweet" },
	}),
}
