local CareItemCatalog = {}

local orderedDefinitions = {
	{
		ItemId = "hay_bale",
		DisplayName = "Hay Bale",
		Description = "Basic hay that fills the stomach well, but keeps excitement low.",
		Price = 1,
		PriceLabel = "1 coin",
		InventoryPath = "Consumables.Food",
		ShopId = "OutdoorStore",
		CareType = "Food",
		NeedKey = "Hunger",
		PromptActionText = "Feed",
		PromptObjectText = "Your horse",
		Tags = { "Food", "Hay", "Starter" },
		MaxStack = 99,
		Effects = {
			NeedGain = 22,
			HappinessGain = 3,
			HealthGain = 0,
			FriendshipGain = 2,
			OverflowYield = 0.24,
			OverflowHealthPenalty = 0.18,
			OverflowHappinessFactor = 0.25,
			DecayBuff = {
				Multiplier = 0.92,
				DurationMinutes = 12,
			},
			MoodText = "Satisfied",
		},
	},
	{
		ItemId = "apple_treat",
		DisplayName = "Apple Treat",
		Description = "A light snack that fills less, but gives a strong happiness bump.",
		Price = 2,
		PriceLabel = "2 coin",
		InventoryPath = "Consumables.Food",
		ShopId = "OutdoorStore",
		CareType = "Food",
		NeedKey = "Hunger",
		PromptActionText = "Feed",
		PromptObjectText = "Your horse",
		Tags = { "Food", "Treat", "Sweet" },
		MaxStack = 99,
		Effects = {
			NeedGain = 12,
			HappinessGain = 10,
			HealthGain = 0,
			FriendshipGain = 5,
			OverflowYield = 0.35,
			OverflowHealthPenalty = 0.12,
			OverflowHappinessFactor = 0.4,
			DecayBuff = {
				Multiplier = 0.96,
				DurationMinutes = 6,
			},
			MoodText = "Cheerful",
		},
	},
	{
		ItemId = "carrot_bunch",
		DisplayName = "Carrot Bunch",
		Description = "Balanced carrots that feed well and still keep the horse in a good mood.",
		Price = 3,
		PriceLabel = "3 coin",
		InventoryPath = "Consumables.Food",
		ShopId = "OutdoorStore",
		CareType = "Food",
		NeedKey = "Hunger",
		PromptActionText = "Feed",
		PromptObjectText = "Your horse",
		Tags = { "Food", "Treat", "Balanced" },
		MaxStack = 99,
		Effects = {
			NeedGain = 18,
			HappinessGain = 7,
			HealthGain = 1,
			FriendshipGain = 4,
			OverflowYield = 0.3,
			OverflowHealthPenalty = 0.15,
			OverflowHappinessFactor = 0.36,
			DecayBuff = {
				Multiplier = 0.9,
				DurationMinutes = 8,
			},
			MoodText = "Content",
		},
	},
	{
		ItemId = "mint_treat",
		DisplayName = "Mint Treat",
		Description = "A favorite bonding snack that gives modest food and extra happiness.",
		Price = 4,
		PriceLabel = "4 coin",
		InventoryPath = "Consumables.Food",
		ShopId = "OutdoorStore",
		CareType = "Food",
		NeedKey = "Hunger",
		PromptActionText = "Feed",
		PromptObjectText = "Your horse",
		Tags = { "Food", "Treat", "Bonding" },
		MaxStack = 99,
		Effects = {
			NeedGain = 10,
			HappinessGain = 12,
			HealthGain = 0,
			FriendshipGain = 6,
			OverflowYield = 0.38,
			OverflowHealthPenalty = 0.1,
			OverflowHappinessFactor = 0.45,
			DecayBuff = {
				Multiplier = 0.82,
				DurationMinutes = 10,
			},
			MoodText = "Playful",
		},
	},
	{
		ItemId = "oat_crunch",
		DisplayName = "Oat Crunch",
		Description = "Dry oats that are simple and steady, with a longer fullness effect.",
		Price = 5,
		PriceLabel = "5 coin",
		InventoryPath = "Consumables.Food",
		ShopId = "OutdoorStore",
		CareType = "Food",
		NeedKey = "Hunger",
		PromptActionText = "Feed",
		PromptObjectText = "Your horse",
		Tags = { "Food", "Oats", "Steady" },
		MaxStack = 99,
		Effects = {
			NeedGain = 16,
			HappinessGain = 5,
			HealthGain = 0,
			FriendshipGain = 3,
			OverflowYield = 0.28,
			OverflowHealthPenalty = 0.14,
			OverflowHappinessFactor = 0.32,
			DecayBuff = {
				Multiplier = 0.88,
				DurationMinutes = 14,
			},
			MoodText = "Calm",
		},
	},
	{
		ItemId = "clover_mix",
		DisplayName = "Clover Mix",
		Description = "A softer meal that feeds less than hay, but stretches hunger decay longer.",
		Price = 6,
		PriceLabel = "6 coin",
		InventoryPath = "Consumables.Food",
		ShopId = "OutdoorStore",
		CareType = "Food",
		NeedKey = "Hunger",
		PromptActionText = "Feed",
		PromptObjectText = "Your horse",
		Tags = { "Food", "Clover", "SlowDecay" },
		MaxStack = 99,
		Effects = {
			NeedGain = 14,
			HappinessGain = 8,
			HealthGain = 0,
			FriendshipGain = 4,
			OverflowYield = 0.32,
			OverflowHealthPenalty = 0.11,
			OverflowHappinessFactor = 0.38,
			DecayBuff = {
				Multiplier = 0.8,
				DurationMinutes = 16,
			},
			MoodText = "Relaxed",
		},
	},
	{
		ItemId = "beet_pellets",
		DisplayName = "Beet Pellets",
		Description = "Dense pellets that feed well and give a small health top-up.",
		Price = 7,
		PriceLabel = "7 coin",
		InventoryPath = "Consumables.Food",
		ShopId = "OutdoorStore",
		CareType = "Food",
		NeedKey = "Hunger",
		PromptActionText = "Feed",
		PromptObjectText = "Your horse",
		Tags = { "Food", "Pellets", "Dense" },
		MaxStack = 99,
		Effects = {
			NeedGain = 20,
			HappinessGain = 4,
			HealthGain = 2,
			FriendshipGain = 3,
			OverflowYield = 0.22,
			OverflowHealthPenalty = 0.16,
			OverflowHappinessFactor = 0.24,
			DecayBuff = {
				Multiplier = 0.86,
				DurationMinutes = 18,
			},
			MoodText = "Restored",
		},
	},
	{
		ItemId = "berry_mash",
		DisplayName = "Berry Mash",
		Description = "Soft mash that fills lightly, but gives one of the best happiness boosts.",
		Price = 8,
		PriceLabel = "8 coin",
		InventoryPath = "Consumables.Food",
		ShopId = "OutdoorStore",
		CareType = "Food",
		NeedKey = "Hunger",
		PromptActionText = "Feed",
		PromptObjectText = "Your horse",
		Tags = { "Food", "Mash", "Premium" },
		MaxStack = 99,
		Effects = {
			NeedGain = 11,
			HappinessGain = 13,
			HealthGain = 1,
			FriendshipGain = 7,
			OverflowYield = 0.4,
			OverflowHealthPenalty = 0.1,
			OverflowHappinessFactor = 0.5,
			DecayBuff = {
				Multiplier = 0.94,
				DurationMinutes = 7,
			},
			MoodText = "Delighted",
		},
	},
	{
		ItemId = "grain_scoop",
		DisplayName = "Grain Scoop",
		Description = "A heavy scoop that fills a lot, but is rougher when force-fed past the limit.",
		Price = 9,
		PriceLabel = "9 coin",
		InventoryPath = "Consumables.Food",
		ShopId = "OutdoorStore",
		CareType = "Food",
		NeedKey = "Hunger",
		PromptActionText = "Feed",
		PromptObjectText = "Your horse",
		Tags = { "Food", "Grain", "Heavy" },
		MaxStack = 99,
		Effects = {
			NeedGain = 28,
			HappinessGain = 2,
			HealthGain = 0,
			FriendshipGain = 2,
			OverflowYield = 0.18,
			OverflowHealthPenalty = 0.22,
			OverflowHappinessFactor = 0.2,
			DecayBuff = {
				Multiplier = 0.87,
				DurationMinutes = 20,
			},
			MoodText = "Full",
		},
	},
	{
		ItemId = "meadow_supper",
		DisplayName = "Meadow Supper",
		Description = "A large meal with the best food value and longest slowdown on hunger decay.",
		Price = 10,
		PriceLabel = "10 coin",
		InventoryPath = "Consumables.Food",
		ShopId = "OutdoorStore",
		CareType = "Food",
		NeedKey = "Hunger",
		PromptActionText = "Feed",
		PromptObjectText = "Your horse",
		Tags = { "Food", "Meal", "Large" },
		MaxStack = 99,
		Effects = {
			NeedGain = 32,
			HappinessGain = 4,
			HealthGain = 1,
			FriendshipGain = 3,
			OverflowYield = 0.16,
			OverflowHealthPenalty = 0.26,
			OverflowHappinessFactor = 0.22,
			DecayBuff = {
				Multiplier = 0.78,
				DurationMinutes = 24,
			},
			MoodText = "Very Full",
		},
	},
	{
		ItemId = "fresh_bucket",
		DisplayName = "Fresh Bucket",
		Description = "Basic water with reliable thirst recovery and no extra frills.",
		Price = 1,
		PriceLabel = "1 coin",
		InventoryPath = "Consumables.Water",
		ShopId = "OutdoorStore",
		CareType = "Water",
		NeedKey = "Thirst",
		PromptActionText = "Give Water",
		PromptObjectText = "Your horse",
		Tags = { "Water", "Starter", "Basic" },
		MaxStack = 99,
		Effects = {
			NeedGain = 20,
			HappinessGain = 2,
			HealthGain = 0,
			FriendshipGain = 2,
			OverflowYield = 0.3,
			OverflowHealthPenalty = 0.14,
			OverflowHappinessFactor = 0.22,
			DecayBuff = {
				Multiplier = 0.92,
				DurationMinutes = 10,
			},
			MoodText = "Hydrated",
		},
	},
	{
		ItemId = "cool_stream",
		DisplayName = "Cool Stream",
		Description = "Less thirst fill than a full bucket, but better comfort and recovery.",
		Price = 2,
		PriceLabel = "2 coin",
		InventoryPath = "Consumables.Water",
		ShopId = "OutdoorStore",
		CareType = "Water",
		NeedKey = "Thirst",
		PromptActionText = "Give Water",
		PromptObjectText = "Your horse",
		Tags = { "Water", "Comfort", "Balanced" },
		MaxStack = 99,
		Effects = {
			NeedGain = 15,
			HappinessGain = 6,
			HealthGain = 0,
			FriendshipGain = 4,
			OverflowYield = 0.36,
			OverflowHealthPenalty = 0.1,
			OverflowHappinessFactor = 0.35,
			DecayBuff = {
				Multiplier = 0.88,
				DurationMinutes = 12,
			},
			MoodText = "Refreshed",
		},
	},
	{
		ItemId = "mint_infusion",
		DisplayName = "Mint Infusion",
		Description = "Light water that does not quench as much, but keeps the horse extra happy.",
		Price = 3,
		PriceLabel = "3 coin",
		InventoryPath = "Consumables.Water",
		ShopId = "OutdoorStore",
		CareType = "Water",
		NeedKey = "Thirst",
		PromptActionText = "Give Water",
		PromptObjectText = "Your horse",
		Tags = { "Water", "Mint", "Happy" },
		MaxStack = 99,
		Effects = {
			NeedGain = 12,
			HappinessGain = 10,
			HealthGain = 0,
			FriendshipGain = 6,
			OverflowYield = 0.4,
			OverflowHealthPenalty = 0.09,
			OverflowHappinessFactor = 0.45,
			DecayBuff = {
				Multiplier = 0.8,
				DurationMinutes = 14,
			},
			MoodText = "Bright",
		},
	},
	{
		ItemId = "apple_splash",
		DisplayName = "Apple Splash",
		Description = "A sweet water mix that makes the horse happier than plain water.",
		Price = 4,
		PriceLabel = "4 coin",
		InventoryPath = "Consumables.Water",
		ShopId = "OutdoorStore",
		CareType = "Water",
		NeedKey = "Thirst",
		PromptActionText = "Give Water",
		PromptObjectText = "Your horse",
		Tags = { "Water", "Sweet", "Treat" },
		MaxStack = 99,
		Effects = {
			NeedGain = 14,
			HappinessGain = 8,
			HealthGain = 0,
			FriendshipGain = 5,
			OverflowYield = 0.35,
			OverflowHealthPenalty = 0.1,
			OverflowHappinessFactor = 0.4,
			DecayBuff = {
				Multiplier = 0.9,
				DurationMinutes = 8,
			},
			MoodText = "Pleased",
		},
	},
	{
		ItemId = "spring_water",
		DisplayName = "Spring Water",
		Description = "Strong thirst recovery with a steady slowdown on future thirst decay.",
		Price = 5,
		PriceLabel = "5 coin",
		InventoryPath = "Consumables.Water",
		ShopId = "OutdoorStore",
		CareType = "Water",
		NeedKey = "Thirst",
		PromptActionText = "Give Water",
		PromptObjectText = "Your horse",
		Tags = { "Water", "Spring", "Steady" },
		MaxStack = 99,
		Effects = {
			NeedGain = 24,
			HappinessGain = 3,
			HealthGain = 0,
			FriendshipGain = 3,
			OverflowYield = 0.24,
			OverflowHealthPenalty = 0.15,
			OverflowHappinessFactor = 0.24,
			DecayBuff = {
				Multiplier = 0.89,
				DurationMinutes = 18,
			},
			MoodText = "Cool",
		},
	},
	{
		ItemId = "rain_barrel",
		DisplayName = "Rain Barrel",
		Description = "A soft refill that is not fancy, but keeps thirst dropping slower for longer.",
		Price = 6,
		PriceLabel = "6 coin",
		InventoryPath = "Consumables.Water",
		ShopId = "OutdoorStore",
		CareType = "Water",
		NeedKey = "Thirst",
		PromptActionText = "Give Water",
		PromptObjectText = "Your horse",
		Tags = { "Water", "Barrel", "SlowDecay" },
		MaxStack = 99,
		Effects = {
			NeedGain = 18,
			HappinessGain = 4,
			HealthGain = 0,
			FriendshipGain = 3,
			OverflowYield = 0.26,
			OverflowHealthPenalty = 0.13,
			OverflowHappinessFactor = 0.26,
			DecayBuff = {
				Multiplier = 0.86,
				DurationMinutes = 20,
			},
			MoodText = "Settled",
		},
	},
	{
		ItemId = "electrolyte_mix",
		DisplayName = "Electrolyte Mix",
		Description = "A stronger water mix that gives thirst back fast and helps health a bit.",
		Price = 7,
		PriceLabel = "7 coin",
		InventoryPath = "Consumables.Water",
		ShopId = "OutdoorStore",
		CareType = "Water",
		NeedKey = "Thirst",
		PromptActionText = "Give Water",
		PromptObjectText = "Your horse",
		Tags = { "Water", "Recovery", "Health" },
		MaxStack = 99,
		Effects = {
			NeedGain = 22,
			HappinessGain = 5,
			HealthGain = 2,
			FriendshipGain = 4,
			OverflowYield = 0.23,
			OverflowHealthPenalty = 0.16,
			OverflowHappinessFactor = 0.28,
			DecayBuff = {
				Multiplier = 0.82,
				DurationMinutes = 16,
			},
			MoodText = "Recovered",
		},
	},
	{
		ItemId = "herbal_cooler",
		DisplayName = "Herbal Cooler",
		Description = "A calmer drink with lower thirst fill, but one of the best mood gains.",
		Price = 8,
		PriceLabel = "8 coin",
		InventoryPath = "Consumables.Water",
		ShopId = "OutdoorStore",
		CareType = "Water",
		NeedKey = "Thirst",
		PromptActionText = "Give Water",
		PromptObjectText = "Your horse",
		Tags = { "Water", "Herbal", "Mood" },
		MaxStack = 99,
		Effects = {
			NeedGain = 13,
			HappinessGain = 9,
			HealthGain = 1,
			FriendshipGain = 6,
			OverflowYield = 0.33,
			OverflowHealthPenalty = 0.09,
			OverflowHappinessFactor = 0.42,
			DecayBuff = {
				Multiplier = 0.78,
				DurationMinutes = 22,
			},
			MoodText = "Peaceful",
		},
	},
	{
		ItemId = "glacier_sip",
		DisplayName = "Glacier Sip",
		Description = "A cold premium drink that restores a lot of thirst, but is less forgiving in excess.",
		Price = 9,
		PriceLabel = "9 coin",
		InventoryPath = "Consumables.Water",
		ShopId = "OutdoorStore",
		CareType = "Water",
		NeedKey = "Thirst",
		PromptActionText = "Give Water",
		PromptObjectText = "Your horse",
		Tags = { "Water", "Cold", "Premium" },
		MaxStack = 99,
		Effects = {
			NeedGain = 26,
			HappinessGain = 4,
			HealthGain = 0,
			FriendshipGain = 3,
			OverflowYield = 0.2,
			OverflowHealthPenalty = 0.17,
			OverflowHappinessFactor = 0.24,
			DecayBuff = {
				Multiplier = 0.84,
				DurationMinutes = 24,
			},
			MoodText = "Recharged",
		},
	},
	{
		ItemId = "golden_trough",
		DisplayName = "Golden Trough",
		Description = "An expensive full drink that restores a lot and keeps thirst low for a long time.",
		Price = 10,
		PriceLabel = "10 coin",
		InventoryPath = "Consumables.Water",
		ShopId = "OutdoorStore",
		CareType = "Water",
		NeedKey = "Thirst",
		PromptActionText = "Give Water",
		PromptObjectText = "Your horse",
		Tags = { "Water", "Large", "Luxury" },
		MaxStack = 99,
		Effects = {
			NeedGain = 30,
			HappinessGain = 6,
			HealthGain = 2,
			FriendshipGain = 5,
			OverflowYield = 0.18,
			OverflowHealthPenalty = 0.2,
			OverflowHappinessFactor = 0.28,
			DecayBuff = {
				Multiplier = 0.76,
				DurationMinutes = 28,
			},
			MoodText = "Pampered",
		},
	},
}

CareItemCatalog.Items = {}
CareItemCatalog.OrderedIds = {}

for _, itemDefinition in ipairs(orderedDefinitions) do
	CareItemCatalog.Items[itemDefinition.ItemId] = itemDefinition
	CareItemCatalog.OrderedIds[#CareItemCatalog.OrderedIds + 1] = itemDefinition.ItemId
end

function CareItemCatalog.GetItemDefinition(itemId)
	return CareItemCatalog.Items[itemId]
end

function CareItemCatalog.GetOrderedIds()
	local orderedIds = {}

	for index, itemId in ipairs(CareItemCatalog.OrderedIds) do
		orderedIds[index] = itemId
	end

	return orderedIds
end

function CareItemCatalog.GetAllItems()
	local items = {}

	for _, itemId in ipairs(CareItemCatalog.OrderedIds) do
		items[#items + 1] = CareItemCatalog.Items[itemId]
	end

	return items
end

function CareItemCatalog.GetItemsByCareType(careType)
	local items = {}

	for _, itemId in ipairs(CareItemCatalog.OrderedIds) do
		local itemDefinition = CareItemCatalog.Items[itemId]
		if itemDefinition and itemDefinition.CareType == careType then
			items[#items + 1] = itemDefinition
		end
	end

	return items
end

function CareItemCatalog.IsCareItem(itemId)
	return CareItemCatalog.Items[itemId] ~= nil
end

return CareItemCatalog
